#!/usr/bin/env python3
"""Development-branch Grapher entrypoint for Neith."""
import index_grapher as base
base.SUMMARIES.update({
    "docs/AGENT_HANDOFF_2026-09-12.md":"Neith implementation handoff recording branch policy, framework thesis, completed protocol/security boundary, and Phase 3 tiny-interpreter direction.",
    "docs/DEVELOPMENT_PLAN_0926-1.md":"Neith pre-1.0 staged development plan covering Application ownership, secure protocol, tiny browser interpreter, state/events, API simplification, DX and hardening.",
    "docs/API_SURFACE_0926-1.md":"Pre-1.0 API migration inventory classifying canonical, compatibility, advanced and candidate-internal Neith concepts.",
    "docs/adr/0001-framework-thesis.md":"Accepted framework thesis: ordinary Go owns behavior/rendering while a thin browser runtime supplies interactivity.",
    "docs/adr/0002-application-runtime-ownership.md":"Accepted Application ownership: one runtime per Application with explicit isolation and lifecycle.",
    "docs/adr/0003-protocol-security-boundary.md":"Accepted finite versioned browser protocol/security boundary; Phase 2 complete and Phase 3 interpreter simplification follows.",
    "application.go":"Canonical Application API owning isolated runtime, configuration, routes, lifecycle and transport policy.",
    "application_test.go":"Application contract tests for routing, shared runtime, isolation, configuration and shutdown behavior.",
    "runtime.go":"Internal Application runtime ownership boundary including handlers, sessions, state, cancellation and connection lifetime.",
    "handler.go":"HTTP/WebSocket/upload bridge binding Application routes to runtime dispatch and server-issued sessions.",
    "conn.go":"Runtime-owned bounded WebSocket transport enforcing origin, protocol version and inbound operation policy.",
    "session.go":"Client-session registry preserving one active connection per opaque server-issued session and supporting reconnect replacement.",
    "session_http.go":"HTTP session boundary generating and issuing opaque HttpOnly server-side session cookies.",
    "session_http_test.go":"Security tests for session cookie issuance, reuse, HTTPS Secure policy and Application page establishment.",
    "errors.go":"Stable lifecycle, dispatch, connection and state/cache errors including ErrApplicationClosed.",
    "dispatch_payloads.go":"Protocol payload definitions including Phase 3 Mutation and FnMutate plus transitional class/DOM compatibility payloads.",
    "dispatch.go":"Go protocol-v1 envelope with finite mutate operation added as the canonical DOM-change primitive; legacy class/dom remain transitional compatibility operations.",
    "dispatch_test.go":"Go protocol tests covering strict v1 envelope behavior, inbound allowlisting and the Phase 3 mutate wire contract.",
    "component.go":"Go component and compatibility helpers; class and focused DOM helpers now translate into the finite mutate protocol primitive.",
    "pkg.go":"Neith configuration and legacy-global compatibility path with Application-local transport/session policy.",
    "static/assets/neith_types.ts":"Browser protocol types including Phase 3 mutate instruction and transitional v1 compatibility operations.",
    "static/assets/protocol.ts":"Strict browser protocol codec validating finite mutate batches and their allowlisted mutation vocabulary.",
    "static/assets/render.ts":"Tiny browser execution helpers including ordered allowlisted mutate batches; legacy class/DOM handlers remain compatibility paths.",
    "static/assets/api.ts":"Finite browser interpreter routing mutate as the canonical focused DOM-change operation while retaining transitional v1 handlers.",
    "static/assets/socket.ts":"Browser WebSocket lifecycle owner; inbound raw JSON is decoded and validated before interpreter execution.",
    "static/assets/uploads.ts":"Same-origin multipart upload helper bound to the server-issued HttpOnly Neith session cookie.",
    "static/assets/tests/setup.ts":"Jest integration compatibility adapter normalizing historical fixtures through the real v1 protocol boundary.",
    "static/assets/tests/protocol.test.ts":"Focused browser protocol contract tests for version validation and v1 response behavior.",
    "static/assets/jest.config.js":"Jest/ts-jest browser-runtime verification configuration.",
    "static/assets/package.json":"Browser development manifest defining tests and reproducible embedded bundle generation.",
    ".github/workflows/grapher-index.yml":"Dev verification workflow gating generated bundle and Grapher publication on Go/browser verification.",
    "AGENTS.md":"Repository agent policy requiring plan/ADR/API awareness, finite-protocol invariants, continuous Grapher use and synchronized artifacts.",
    "scripts/index_grapher_dev.py":"Development Grapher entrypoint adding semantic summaries for active architecture and Phase 3 implementation artifacts.",
    "docs/README.md":"Neith documentation index and mental-model entrypoint linking active plans, architecture, usage and repository references."
})
if __name__ == "__main__": base.main()
